### ISSUE TITLE
Bug in media_clock_server.xc with PLL_OUTPUT_TIMING_CHECK set

### ISSUE THREAD

**Issue by pthedinger** [xmos/lib_tsn#12]
If PLL_OUTPUT_TIMING_CHECK is set to 1 then lib_tsn fails to compile:

lib_tsn/lib_tsn/src/media_clock/media_clock_server.xc:387:15: error: use of undeclared identifer `x'
          if (x==3)

**Comment by larry-xmos** [comment]
Fixed in f80386bd56210a586766e13eccfb0d34917ee783
