### ISSUE TITLE
Spelling error in avb.xc

### ISSUE THREAD

**Issue by ahogen** [xmos/lib_tsn#29]
There are 8 references to `stream_mutlicast_filter` in [avb.xc](https://github.com/xmos/lib_tsn/blob/master/lib_tsn/src/avb/avb.xc). Try as I might, I can't find the word `mutlicast` in the dictionary... 😉 

Should be `stream_multicast_filter`.

**Comment by larry-xmos** [comment]
Thanks for the report, I've corrected this now
