### ISSUE TITLE
AN00202 main.xc comment and code conflict

### ISSUE THREAD

**Issue by ahogen** [xmos/lib_tsn#30]
In `main.xc` of AN00202 ([click here](https://github.com/xmos/lib_tsn/blob/master/examples/AN00202_gige_avb_i2s_demo/src/main.xc#L136-L138)) the code comment states we are selecting the 24.576KHz clock. The code doesn't seem to line up with what the xCORE-200 Multichannel Audio board documentation says. I'm not sure which one it's supposed to be as, from what I understand, the PLL used could be factory programmed either way.

```
// Select 48Khz family clock (24.576Mhz)
mclk_select.output(0);                // <---- ?
pll_select.output(1);
```

![capture](https://cloud.githubusercontent.com/assets/6827790/26794232/bab4face-49d5-11e7-8fb5-c291a02ab081.PNG)

**Comment by larry-xmos** [comment]
MCLK_FSEL 0 will indeed select 22.5792MHz. But PLL_SELECT 1 means we don't use CLK1 from the PL611, instead we use output of the CS2100 PLL.

![pll based clocking](https://user-images.githubusercontent.com/712774/27691940-60f878c4-5cdd-11e7-9400-dbe85a915560.png)

I will correct the comment

**Comment by larry-xmos** [comment]
Thanks for the report
